<?php

namespace App\Filament\Resources\System;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ForceDeleteBulkAction;
use Filament\Actions\RestoreBulkAction;
use App\Filament\Resources\System\PageRouteResource\Pages;
use App\Helpers\PageRouteHelper;
use App\Helpers\PageTypesHelper;
use App\Models\System\PageRoute;
use App\Services\System\UrlService;
use Filament\Forms\Components\Checkbox;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Resources\Resource;
use Filament\Tables\Columns\CheckboxColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PageRouteResource extends Resource
{
    protected static ?string $model = PageRoute::class;

    protected static string|\UnitEnum|null $navigationGroup = 'Nastavení webu';
    protected static ?int $navigationSort = 20;
    protected static string|\BackedEnum|null $navigationIcon = 'heroicon-o-map';
    protected static ?string $navigationLabel = 'Page Routes';

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->schema([
                TextInput::make('route_name')
                    ->required()
                    ->maxLength(255),
                TextInput::make('route_path')
                    ->required()
                    ->maxLength(255),
                Select::make('route_method')
                    ->required()
                    ->options([
                        'get' => 'GET',
                        'post' => 'POST',
                        'put' => 'PUT',
                        'patch' => 'PATCH',
                        'delete' => 'DELETE',
                    ]),
                Select::make('template')
                    ->label('Template')
                    ->options(PageTypesHelper::$pageTypesLabels)
                    ->nullable()
                    ->live()
                    ->afterStateUpdated(function (Set $set, ?string $state) {
                        if ($state && isset(PageTypesHelper::$pageTypesToControllersMap[$state])) {
                            $set('route_controller', PageTypesHelper::$pageTypesToControllersMap[$state]);
                        }
                    }),
                Select::make('route_controller')
                    ->label('Controller')
                    ->options(PageRouteHelper::getControllers())
                    ->required()
                    ->reactive(),

                Select::make('route_action')
                    ->label('Akce')
                    ->options(fn (callable $get) =>
                    $get('route_controller')
                        ? PageRouteHelper::getActions($get('route_controller'))
                        : []
                    )
                    ->required()
                    ->reactive(),
                Select::make('route_lang')
                    ->required()
                    ->options(function () {
                        $languages = \App\Models\System\Language::all()->pluck('name', 'locale')->toArray();
                        return $languages;
                    })
                    ->default(function () {
                        return UrlService::defaultLang();
                    }),
                Checkbox::make('is_active')
                    ->label('Aktivní'),
                Checkbox::make('disable_auto_route')
                    ->label('Negenerovat automaticky')
                    ->helperText('Route sa bude generovat iba když bude obsahovat i slug! Použití jedine pri stránkach'),
            ])->columns(2);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('route_name')
                    ->searchable(),
                TextColumn::make('route_path')
                    ->searchable(),
                TextColumn::make('route_method')
                    ->searchable(),
                TextColumn::make('template')
                    ->searchable(),
                TextColumn::make('route_lang')
                    ->searchable(),
                TextColumn::make('generated')
                    ->searchable(),
                TextColumn::make('page.title')
                    ->label('Generated by Page')
                    ->default('-'),
                CheckboxColumn::make('is_active')
                    ->label('Aktivní'),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                TrashedFilter::make(),
            ])
            ->actions([
                EditAction::make(),
            ])
            ->bulkActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                    ForceDeleteBulkAction::make(),
                    RestoreBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPageRoutes::route('/'),
            'create' => Pages\CreatePageRoute::route('/create'),
            'edit' => Pages\EditPageRoute::route('/{record}/edit'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->withoutGlobalScopes([
                SoftDeletingScope::class,
            ]);
    }
}
